fix: Add dummy support of --prefix CLI option
href: https://github.com/math-comp/multinomials/pull/49#issuecomment-953721813

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,13 +2,13 @@
 # Erik Martin-Dorel, 2021 (configure script for SsrMultinomials)
 #
 # ARG_OPTIONAL_SINGLE([native-compiler],[],[Pre-compiles .coq-native/* files (yes|no)],[])
+# ARG_OPTIONAL_SINGLE([prefix],[],[Dummy option (its value is ignored) for Nix compatibility],[])
 # ARG_HELP([configure script for SsrMultinomials])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
+### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
-# Generated online by https://argbash.io/generate
 
 die()
 {
@@ -27,12 +27,14 @@ begins_with_short_option()
 
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_native_compiler=
+_arg_prefix=
 
 print_help()
 {
 	printf '%s\n' "configure script for SsrMultinomials"
-	printf 'Usage: %s [--native-compiler <arg>] [-h|--help]\n' "$0"
-	printf '\t%s\n' "--native-compiler: Pre-compile .coq-native/* files (yes|no)"
+	printf 'Usage: %s [--native-compiler <arg>] [--prefix <arg>] [-h|--help]\n' "$0"
+	printf '\t%s\n' "--native-compiler: Pre-compiles .coq-native/* files (yes|no)"
+	printf '\t%s\n' "--prefix: Dummy option (its value is ignored) for Nix compatibility"
 	printf '\t%s\n' "-h, --help: Prints help"
 }
 
@@ -49,6 +51,14 @@ parse_commandline()
 				;;
 			--native-compiler=*)
 				_arg_native_compiler="${_key##--native-compiler=}"
+				;;
+			--prefix)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_prefix="$2"
+				shift
+				;;
+			--prefix=*)
+				_arg_prefix="${_key##--prefix=}"
 				;;
 			-h|--help)
 				print_help
@@ -67,6 +77,8 @@ parse_commandline()
 }
 
 parse_commandline "$@"
+
+# OTHER STUFF GENERATED BY Argbash
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
@@ -89,6 +101,9 @@ coq_native_compiler() {
 }
 
 main() {
+    if [ -n "$_arg_prefix" ]; then
+        echo "Warning: Ignore argument '--prefix=$_arg_prefix'" >&2
+    fi
     if coq_native_compiler; then
         echo 'coq-native support enabled!' >&2
         sed -e 's/;coq-native-disabled; \?//' "$dir/src/dune.in" > "$dir/src/dune"
