Make `(mode native)` configurable
So we can do:
- ./configure --native-compiler yes
- ./configure --native-compiler no
- ./configure  # now implying *no* native-compiler if coq = 8.12.x

As a result, the script is simpler: it needs not check coq's version.

Further, it becomes easier to package multinomials in Nix (and opam).

CI: Update coq-mathcomp-multinomials.opam & ci.yml files accordingly.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,38 +1,91 @@
 #!/usr/bin/env bash
 # Erik Martin-Dorel, 2021 (configure script for SsrMultinomials)
+#
+# ARG_OPTIONAL_SINGLE([native-compiler],[],[Pre-compiles .coq-native/* files (yes|no)],[])
+# ARG_HELP([configure script for SsrMultinomials])
+# ARGBASH_GO()
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+# Generated online by https://argbash.io/generate
+
+die()
+{
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
+	echo "$1" >&2
+	exit "${_ret}"
+}
+
+begins_with_short_option()
+{
+	local first_option all_short_options='h'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
+
+# THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_native_compiler=
+
+print_help()
+{
+	printf '%s\n' "configure script for SsrMultinomials"
+	printf 'Usage: %s [--native-compiler <arg>] [-h|--help]\n' "$0"
+	printf '\t%s\n' "--native-compiler: Pre-compile .coq-native/* files (yes|no)"
+	printf '\t%s\n' "-h, --help: Prints help"
+}
+
+parse_commandline()
+{
+	while test $# -gt 0
+	do
+		_key="$1"
+		case "$_key" in
+			--native-compiler)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_native_compiler="$2"
+				shift
+				;;
+			--native-compiler=*)
+				_arg_native_compiler="${_key##--native-compiler=}"
+				;;
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			*)
+				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
+				;;
+		esac
+		shift
+	done
+}
+
+parse_commandline "$@"
+
+### END OF CODE GENERATED BY Argbash (sortof) ### ])
+# [ <-- needed because of Argbash
 
 dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )
-
-le_version() {
-    [ "$(printf '%s\n' "$1" "$2" | sort -V -u | tail -n1)" = "$2" ]
-}
-
-# BEGIN TESTS
-fail_test() {
-    echo "error: test $* failed" >&2; exit 2
-}
-unit_tests() {
-    le_version "8.12.1" "8.12.1" || fail_test 0
-    le_version "8.9.0" "8.12.1" || fail_test 1
-    le_version "8.12.1" "8.12.2" || fail_test 2
-    le_version "8.12.2" "8.13.0" || fail_test 3
-}
-# unit_tests
-# END TESTS
-
-coq_version() {
-    coqc --version | grep version | \
-        sed -e 's/^.*version \([-0-9a-z.+~]\+\)\( .*\)\?$/\1/'
-}
 
 coq_native_compiler_default() {
     coqc -config | grep -q 'COQ_NATIVE_COMPILER_DEFAULT=yes'
 }
 
 coq_native_compiler() {
-    cv=$(coq_version)
-    { le_version "8.12.1" "$cv" && ! le_version "8.13.0" "$cv"; } \
-        || coq_native_compiler_default
+    case "$_arg_native_compiler" in
+        yes)
+            return 0 ;;
+        no)
+            return 1 ;;
+        *)
+            coq_native_compiler_default ;;
+    esac
 }
 
 main() {
@@ -40,11 +93,11 @@ main() {
         echo 'coq-native support enabled!' >&2
         sed -e 's/;coq-native-disabled; \?//' "$dir/src/dune.in" > "$dir/src/dune"
     else
+        echo 'coq-native support disabled.' >&2
         cat "$dir/src/dune.in" > "$dir/src/dune"
     fi
 }
 
-# Credits: https://stackoverflow.com/a/28776166/9164010
-( return 0 2>/dev/null ) || main
-# ./configure => Run main
-# . configure => Don't run main (useful in .github/workflows/ci.yml)
+main
+
+# ] <-- needed because of Argbash
