Add coq-native support (if available) as per CEP 48 (#45)
* For details, see:

  - https://opam.ocaml.org/packages/coq-native/
  - CEP 48 <https://github.com/coq/ceps/blob/master/text/048-packaging-coq-native.md#note-to-library-developers-and-package-maintainers>

* can be reverted anytime after the merge of https://github.com/coq/opam-coq-archive/pull/1835
   and the rebuild of `mathcomp/mathcomp:1.12.0-coq-8.12`

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,3 +1,5 @@
+name: Docker CI
+
 on: [push, pull_request]
 
 jobs:
@@ -6,12 +8,59 @@ jobs:
     strategy:
       matrix:
         image:
-        -  mathcomp/mathcomp:1.12.0-coq-8.10
-        -  mathcomp/mathcomp:1.12.0-coq-8.11
-        -  mathcomp/mathcomp:1.12.0-coq-8.12
+          - mathcomp/mathcomp:1.12.0-coq-8.10
+          - mathcomp/mathcomp:1.12.0-coq-8.11
+          - mathcomp/mathcomp:1.12.0-coq-8.12 # 8.12.1+ support ocaml/dune#3210
+          - coqorg/coq:8.13-native-ocaml-4.07 # with the coq-native opam pkg
+          - coqorg/coq:8.14-native-ocaml-4.07 # with the coq-native opam pkg
+          - mathcomp/mathcomp:1.12.0-coq-8.13 # (without coq-native for now)
+          - mathcomp/mathcomp:1.12.0-coq-8.14 # (without coq-native for now)
+          # the previous comments refer to https://github.com/coq/ceps/pull/48
       fail-fast: false
     steps:
-    - uses: actions/checkout@v2
-    - uses: coq-community/docker-coq-action@v1
-      with:
-        custom_image: ${{ matrix.image }}
+      - uses: actions/checkout@v2
+      - uses: coq-community/docker-coq-action@v1
+        env:
+          LIBRARY_NAME: 'SsrMultinomials'
+          ROOT_THEORIES: 'mpoly monalg'
+        with:
+          opam_file: 'coq-mathcomp-multinomials.opam'
+          custom_image: ${{ matrix.image }}
+          export: 'LIBRARY_NAME ROOT_THEORIES'
+          # Note: these native-compiler tests are generic,
+          # thanks to env variables & the configure script
+          after_script: |
+            startGroup "Print native_compiler status"
+              coqc -config
+              . configure  # sourcing mandatory
+              coq_version
+            endGroup
+            # Note: Replace with "if coq_native_compiler"
+            # to also test with Coq 8.12.1+
+            if coq_native_compiler_default; then
+              startGroup "Workaround permission issue"
+                sudo chown -R coq:coq .  # <--(§)
+              endGroup
+              startGroup "Check native_compiler on a test file"
+                printf '%s\n' "From $LIBRARY_NAME Require Import $ROOT_THEORIES." > test.v
+                coqc -debug -native-compiler yes test.v > stdout.txt || ret=$?
+                cat stdout.txt
+                ( exit "${ret:-0}" )
+              endGroup
+              # in practice, we get ret=0 even if deps were not native-compiled
+              # but the logs are useful...(*), so we keep this first test group
+              # and add another test group which is less verbose, but stricter.
+              startGroup "Check installation of .coq-native/ files"
+                set -o pipefail
+                # fail noisily if ever 'find' gives 'No such file or directory'
+                num=$(find "$(coqc -where)/user-contrib/$LIBRARY_NAME" -type d -name ".coq-native" | wc -l)
+                [ "$num" -gt 0 ]
+              endGroup
+            fi
+      - name: Revert permissions
+        # to avoid a warning at cleanup time
+        if: ${{ always() }}
+        run: sudo chown -R 1001:116 .  # <--(§)
+
+#(§)=> https://github.com/coq-community/docker-coq-action#permissions
+#(*)=> Cannot find native compiler file /home/coq/.opam/4.07.1/lib/coq/user-contrib/SsrMultinomials/.coq-native/NSsrMultinomials_ssrcomplements.cmxs
